repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, server, simulation_core]
      - id: ruff-format
        args: [--config=pyproject.toml, server, simulation_core]